version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: text_analyzer_db
    restart: always
    environment:
      POSTGRES_DB: text_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: text_analyzer_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_NAME: text_analyzer
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3000
      NODE_ENV: production
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      JWT_SECRET: your_jwt_secret
      CLIENT_URL: http://localhost:5000

  frontend:
    build: ./frontend
    container_name: text_analyzer_frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

volumes:
  postgres_data:
